# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ece0b7c2ec9cbe20b691777de372bcf147ee6a0f439e17f1b5c64e71dcfe00407c6a258f19ed597822b893be7d2dea27973c3064c5e2c8c5b6c5dd517a8261c

test:
  secret_key_base: 23216102bbff9f8567de202a4cd1184e182de9ac203e132f9638fc1d3b6d830a796f32043eedf550dd6fd84d6f012befbce7c8d924fbe7860103ae296d82075c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
