# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76f85f226a2deead7dfa64e8df85e20377f637ab5ff25e61ccba150affa61d6c88b4fccb85e4d9441be9c38776e4258ab50b489451a3f2372fe76648d9bcd3e0

test:
  secret_key_base: 791f77cdb0cd270a16ad611481c341fc5eb2b50129f6e233b152e46b06ea8367c41f48f50d99123c5891655ef7f747d01542308e08f06367b5af0bf12c26c9c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
